### ISSUE TITLE
Agregar acotación en apartado de inclusión de archivos JavaScript

### ISSUE THREAD

**Issue by smokenight** [I2BTech/guia-para-el-codigo-frontend#2]
Se debe señalar que las librerías modernizr y html5shiv se deben incluir obligatoriamente en el header debido a la funcionalidad que llevan a cabo. Todas las demás librerías, plugins, etc. deben ir antes del cierre del BODY tal como se señala.

**Comment by juanbrujo** [comment]
gracias, agregare esas excepciones

**Comment by juanbrujo** [comment]
@smokenight agregado lo sugerido en 5709fe13aaa724d48ed392716bc754e316710800 gracias.
